image: sirehna/dind

services:
    - docker:dind

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - deploy

build:
    stage: build
    before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    script:
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE:test" --tag "$CI_REGISTRY_IMAGE:test" .
    - docker push "$CI_REGISTRY_IMAGE:test"
    except:
    - tags

deploy:
    stage: deploy
    before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    script:
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull --cache-from "$CI_REGISTRY_IMAGE:latest" --tag "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    only:
    - tags
